"""Emit the palette for consumers that are not Qt.

One app in the family is an Electron/WebGL viewer rather than a Qt app. It cannot use the
stylesheet, but it must use the same colours, and a hand-kept copy is the one option that is
definitively wrong: 50-odd tokens times two modes is 100 values, and the whole reason ``Palette``
is a frozen dataclass with no defaults is that a missing token is a ``TypeError`` at import rather
than a colour that silently comes out empty. A CSS ``var()`` that resolves to nothing does not
error -- it inherits, or falls back to black.

So the values are generated, and the generated files are checked in. The consuming app has no
build step, and neither its npm packaging nor its installer should need a Python toolchain just to
get colours. A CI step that regenerates and fails on a non-empty diff keeps them honest.

Two formats, because the consumer needs both:

- **CSS custom properties** for the stylesheet.
- **A JS module** for the 3D scene, where colours reach ``THREE.Color`` as ``0xRRGGBB`` integers.
  ``getComputedStyle`` per frame is not a reasonable way to read a custom property, so the numbers
  are emitted directly.

This module is Qt-free like the rest of the core, so the generator runs in a plain interpreter.
"""

from __future__ import annotations

import json
from dataclasses import fields

from .geometry import RADIUS_CTRL, RADIUS_PANEL, RADIUS_PILL, RADIUS_PILL_LG, S1, S2, S3, S4, S5, S6, S7
from .palette import DARK, LIGHT, Ink, Palette

PREFIX = "--ft"

_BANNER = (
    "/* Generated by forecast_theme.export -- do not edit.\n"
    " *\n"
    " * Regenerate with:  python -m forecast_theme.export <out-dir>\n"
    " * The values come from the same Palette the Qt apps use, so a colour cannot drift between\n"
    " * this app and the others without the diff showing up here.\n"
    " */\n"
)


def _name(field: str) -> str:
    return f"{PREFIX}-{field.replace('_', '-')}"


def _channels(value: "str | Ink") -> tuple[int, int, int, float]:
    if isinstance(value, Ink):
        return value.r, value.g, value.b, value.a
    text = value.lstrip("#")
    return (*(int(text[i:i + 2], 16) for i in (0, 2, 4)), 1.0)


def _colour_fields() -> list[str]:
    """Every palette field that is a colour -- ``name`` and ``dark`` are not."""
    return [f.name for f in fields(Palette) if f.name not in ("name", "dark")]


def css_block(pal: Palette, selector: str) -> str:
    """One ``selector { ... }`` block of custom properties for ``pal``."""
    lines = [f"{selector} {{"]
    for field in _colour_fields():
        value = getattr(pal, field)
        r, g, b, a = _channels(value)
        lines.append(f"  {_name(field)}: {value};")
        # The channels as well as the colour, so a one-off alpha is
        # rgba(var(--ft-accent-rgb), 0.3) rather than a new token nobody maintains.
        lines.append(f"  {_name(field)}-rgb: {r}, {g}, {b};")
    lines.append("}")
    return "\n".join(lines)


def css_vars() -> str:
    """Both palettes as custom properties, keyed by a ``data-theme`` attribute on the root.

    The renderer is handed a resolved mode -- light or dark -- and never learns that "system"
    exists, which keeps the cascade a plain two-way switch instead of a fight between
    ``prefers-color-scheme`` and an explicit override.
    """
    parts = [_BANNER, css_block(DARK, ':root, :root[data-theme="dark"]'), "",
             css_block(LIGHT, ':root[data-theme="light"]'), "", _geometry_block()]
    return "\n".join(parts) + "\n"


def _geometry_block() -> str:
    lines = [
        "/* Geometry. Note the pill radii are NOT the Qt values: that Qt build does not clamp a",
        " * radius at half the widget height, so it needs a measured number, while CSS clamps",
        " * correctly and 999px is the right way to say 'capsule'. Do not 'fix' these to match.",
        " */",
        ":root {",
        f"  {PREFIX}-radius-panel: {RADIUS_PANEL}px;",
        f"  {PREFIX}-radius-ctrl: {RADIUS_CTRL}px;",
        f"  {PREFIX}-radius-pill: 999px;",
        f"  {PREFIX}-radius-pill-lg: 999px;",
    ]
    for index, value in enumerate((S1, S2, S3, S4, S5, S6, S7), start=1):
        lines.append(f"  {PREFIX}-s{index}: {value}px;")
    lines.append("}")
    lines.append(f"/* Qt's measured pill radii, for reference: {RADIUS_PILL}px / {RADIUS_PILL_LG}px */")
    return "\n".join(lines)


def js_module() -> str:
    """Both palettes as a JS module, with each colour in the three forms a 3D scene needs."""
    def entries(pal: Palette) -> dict:
        out = {}
        for field in _colour_fields():
            r, g, b, a = _channels(getattr(pal, field))
            out[field] = {
                "hex": f"#{r:02x}{g:02x}{b:02x}",
                "int": (r << 16) + (g << 8) + b,
                "rgb": [r, g, b],
                "a": round(a, 3),
            }
        return out

    body = {"light": entries(LIGHT), "dark": entries(DARK)}
    return (
        "// Generated by forecast_theme.export -- do not edit.\n"
        "//\n"
        "// Regenerate with:  python -m forecast_theme.export <out-dir>\n"
        "//\n"
        "// `int` is the form THREE.Color wants (0xRRGGBB). Reading a CSS custom property through\n"
        "// getComputedStyle once per frame is not a reasonable way to colour a scene, which is why\n"
        "// the numbers are here rather than only in the stylesheet.\n"
        "export const PALETTES = " + json.dumps(body, indent=2) + ";\n\n"
        "/** The palette for a resolved mode ('light' or 'dark'). */\n"
        "export function palette (mode) {\n"
        "  return PALETTES[mode === 'light' ? 'light' : 'dark'];\n"
        "}\n"
    )


def write(out_dir) -> list[str]:
    """Write both artifacts into ``out_dir``. Returns the paths written."""
    from pathlib import Path

    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in (("theme.generated.css", css_vars()),
                       ("theme.generated.js", js_module())):
        path = directory / name
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(str(path))
    return written


if __name__ == "__main__":
    import sys

    for written in write(sys.argv[1] if len(sys.argv) > 1 else "."):
        print(f"wrote {written}")
